# Generated by Django 3.0.6 on 2020-05-16 00:39

from django.db import migrations
from backend.api.manual_migration import import_dataset


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    initial = True
    operations = [
        migrations.RunPython(import_dataset, reverse_code=migrations.RunPython.noop)
    ]
