# Generated by Django 2.1.4 on 2020-05-13 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgID', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(max_length=15, blank=True, default="")),
                ('imgStaticPath', models.CharField(max_length=200)),
            ],
        ),
    ]
