# Generated by Django 3.0.7 on 2020-07-11 16:54

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.models import User


DJANGO_APP_NAME = "api"


def populate_user_profiles(apps, schema_editor):
    Profile = apps.get_model(DJANGO_APP_NAME, 'Profile')
    db_alias = schema_editor.connection.alias
    for user in User.objects.all():
        Profile.objects.get_or_create(user_id=user.id, is_test=False)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200519_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(populate_user_profiles, reverse_code=migrations.RunPython.noop),
    ]
