# Generated by Django 3.0.6 on 2020-05-13 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200513_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='annotations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
    ]
