# Generated by Django 3.0.6 on 2020-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200513_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
