# Generated by Django 3.0.6 on 2020-05-16 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgID', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(blank=True, default='', max_length=15)),
                ('imgStaticPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='api.Image', to_field='imgID')),
            ],
            options={
                'unique_together': {('annotator', 'image')},
            },
        ),
    ]
